openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/MRCHRISCARLETON/BottomTime/1.0.0
  - description: Development
    url: https://api-dev.bottomti.me
  - description: Production
    url: https://api.bottomti.me

info:
  description: This is the API specifications for the Bottom Time application.
  version: "1.0.0"
  title: Bottom Time
  contact:
    email: mrchriscarleton@gmail.com
    name: Chris Carleton
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /auth/login:
    post:
      security: []
      summary: Attempt to login a user with username and password pair.
      operationId: loginUser
      description: Logs in a user given their username and password.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - usernameOrEmail
                - password
              properties:
                usernameOrEmail:
                  type: string
                  description: The user's username or email address.
                  example: 'mike_42'
                password:
                  type: string
                  description: The user's password.
                  example: '*********'
      responses:
        '200':
          description: |
            Successful login! User account info will be returned and a session
            cookie will be set in the response header.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/ValidationErrorResponse'
        '401':
          description: Login attempt failed due to invalid username or password.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '500':
          $ref: '#/components/responses/ServerErrorResponse'


  /auth/logout:
    get:
      security:
        - SessionCookie: []
      summary: Logout the current user and end their session.
      operationId: logoutUser
      description: Logs the current user out of their session and redirects back to the home page.
      responses:
        '302':
          description: Redirect back to home page with session cookie set.
          headers:
            Location:
              schema:
                type: string

  /auth/me:
    get:
      security: []
      summary: Get account information for the currently logged in user.
      operationId: getCurrentUser
      description: |
        Retrieves information on the currently logged in user.
      responses:
        '200':
          description: Information on the currently logged in user (if any).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentUser'

  /users:
    get:
      summary: Search for user accounts matching a criteria.
      security:
        - SessionCookie: [admin]
      operationId: searchUsers
      description: Searches for user accounts given a search criteria.
      parameters:
        - in: query
          name: query
          description: A text string that will be searched for amongst the user data.
          required: false
          schema:
            type: string
        - in: query
          name: role
          description: |
            Filters users to only show the indicated role.
            * 100 = Regular user
            * 200 = Administrator
          required: false
          schema:
            type: number
            format: int32
            enum:
              - 100
              - 200
        - in: query
          name: sortBy
          description: |
            The field on which the the results should be sorted.
            The default is `username` unless a query string is provided; then it becomes `relevance`.
          required: false
          schema:
            type: string
            enum:
              - memberSince
              - relevance
              - username
        - in: query
          name: sortOrder
          description: The order in which the results should be returned.
          required: false
          schema:
            type: string
            enum:
              - asc
              - desc
        - in: query
          name: skip
          description: |
            Indicates how many results should be skipped over. (Useful for paging results.)
            Minimum value is `0`.
          required: false
          schema:
            type: number
            format: int32
        - in: query
          name: limit
          description: |
            Indicates the maximum number of results to return in the current request. Must be at least `1` and no greater than `200`.
            The default is `100`.
          required: false
          schema:
            type: number
            format: int32
      responses:
        '200':
          description: |
            The request succeeded and the request body will contain an array of users
            matching the search criteria.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/ValidationErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedErrorResponse'
        '403':
          $ref: '#/components/responses/AdminOnlyErrorResponse'
        '500':
          $ref: '#/components/responses/ServerErrorResponse'

  /user/{usernameOrEmail}:
    get:
      summary: Retrieve user account info.
      operationId: getUser
      description: |
        Will attempt to retrieve a user's account information.
      security:
        - SessionCookie: [admin]
      parameters:
        - $ref: '#/components/parameters/UsernameParameter'
      responses:
        200:
          description: |
            The request succeeded and the user account information is returned in the response body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        401:
          $ref: '#/components/responses/UnauthorizedErrorResponse'
        403:
          $ref: '#/components/responses/AdminOnlyErrorResponse'
        404:
          description: |
            An account matching the requested username or email address could not be found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
    head:
      summary: Check for existence of username or email address.
      operationId: userExists
      security: []
      parameters:
        - $ref: '#/components/parameters/UsernameParameter'
      description: |
        This call can be used to quickly determine if a username or email address is already in use on the site.
      responses:
        200:
          description: Username or email address exists in the database.
        404:
          description: The requested username or email was not found in the database.

components:
  securitySchemes:
    SessionCookie:
      type: apiKey
      name: bottomtime.platform
      in: cookie

  parameters:
    UsernameParameter:
      in: path
      name: usernameOrEmail
      required: true
      description: |
        The username (or email address) that uniquely identifies the target user account.
      schema:
        type: string

  schemas:
    Error:
      type: object
      description: A standard error resposne. This format is used when returning any kind of error.
      required:
        - httpPath
        - httpMethod
      properties:
        httpPath:
          type: string
          description: The HTTP path that the request was made to.
          example: '/profiles/Bob_47'
        httpMethod:
          type: string
          description: The HTTP method that was used in the request.
          example: 'POST'
        username:
          type: string
          description: The username identifying the user that made the request.
          example: 'Rick.M'

    ServerError:
      allOf:
        - $ref: '#/components/schemas/Error'
        - type: object
          required:
            - message
            - statusCode
          properties:
            message:
              type: string
              description: The error message. Will provide a brief description of what went wrong.
              example: 'An unexpected server error has occurred.'
            statusCode:
              type: number
              format: int32
              description: A 500 error code.
              example: 500

    NotFoundError:
      allOf:
        - $ref: '#/components/schemas/Error'
        - type: object
          required:
            - message
            - statusCode
          properties:
            message:
              type: string
              description: The error message. Will provide a brief description of what went wrong.
              example: 'The requested resource could not be found.'
            statusCode:
              type: number
              format: int32
              description: A 404 error code.
              example: 404

    UnauthorizedError:
      allOf:
        - $ref: '#/components/schemas/Error'
        - type: object
          required:
            - message
            - statusCode
          properties:
            message:
              type: string
              description: The error message. Will provide a brief description of what went wrong.
              example: 'Unable to process request. Please log in and try the request again.'
            statusCode:
              type: number
              format: int32
              description: A 401 error code.
              example: 401

    ForbiddenError:
      allOf:
        - $ref: '#/components/schemas/Error'
        - type: object
          required:
            - message
            - statusCode
          properties:
            message:
              type: string
              description: The error message. Will provide a brief description of what went wrong.
              example: |
                Requested operation was denied. You are not authorized to perform the requested action.
            statusCode:
              type: number
              format: int32
              description: A 403 error code.
              example: 403

    ValidationError:
      allOf:
        - $ref: '#/components/schemas/Error'
        - type: object
          required:
            - message
            - statusCode
          properties:
            message:
              type: string
              description: The error message. Will provide a brief description of what went wrong.
              example: |
                Your request was malformed or contained invalid data.
            statusCode:
              type: number
              format: int32
              description: A 400 error code.
              example: 400
            details:
              type: array
              items:
                type: object
                properties:
                  message:
                    type: string
                    example: 'First name must be a string'
                  path:
                    type: string
                    example: 'name.firstName'

    User:
      type: object
      description: Represents a user of the application. This object will capture all of a user's information.
      required:
        - emailVerified
        - hasPassword
        - id
        - isLockedOut
        - memberSince
        - role
        - username
      properties:
        email:
          type: string
          description: User's email address. Used for authentication and communication.
          format: email
          example: micheller_27@gmail.com
        emailVerified:
          description: Indicates whether the user's email address has been verified or not.
          type: boolean
        hasPassword:
          type: boolean
          description: Inidicates whether the user has a password set on their account or not. (Some users may choose to use OAuth to sign in and will not have a password.)
        lastLogin:
          type: string
          description: The time and date (UTC) at which the user was last logged into the application.
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        lastPasswordChange:
          type: string
          description: The time and date (UTC) at which the user last changed or set their password.
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        id:
          type: string
          format: uuid
          description: A globally-unique identifier that can be used to identify the user's account.
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        isLockedOut:
          type: boolean
          description: Indicates whether or not the user's account is currently suspended. (Locked out accounts are prevented from signing in.)
        memberSince:
          type: string
          format: date-time
          description: Date and time (UTC) at which the user's account was first created.
          example: '2016-08-29T09:12:33.001Z'
        profile:
          $ref: '#/components/schemas/Profile'
        role:
          type: number
          format: int32
          description: The user's security role. 100 = normal user. 200 = admin user.
          example: 100
          enum:
            - 100
            - 200
        username:
          type: string
          description: The user's unique username. This is used for logging in and for retrieving account information.
          example: MichelleR_27

    CurrentUser:
      description: Information on the currently logged-in user.
      allOf:
        - type: object
          required:
            - anonymous
          properties:
            anonymous:
              type: boolean
              description: |
                Indicates if the user is anonymous (not currently authenticated.)
                If true, then the other properties will be omitted.
              example: false
        - $ref: '#/components/schemas/User'

    Profile:
      type: object
      description: Describes a user's profile information.
      required:
        - memberSince
        - profileVisibility
        - userId
        - username
      properties:
        memberSince:
          type: string
          format: date-time
          description: Date and time (UTC) at which the user's account was first created.
          example: '2016-08-29T09:12:33.001Z'
        profileVisibility:
          type: string
          description: Indicates who is authorized to view this user's profile information.
          enum:
            - private
            - friends
            - public
        userId:
          type: string
          format: uuid
          description: A globally-unique identifier that can be used to identify the user's account.
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        username:
          type: string
          description: The user's unique username. This is used for logging in and for retrieving account information.
          example: MichelleR_27

  responses:
    AdminOnlyErrorResponse:
      description: The request was denied because the user is not a site administrator.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ForbiddenError'

    UnauthorizedErrorResponse:
      description: |
        The operation was denied because the user is unauthenticated or did not provide the requisite session cookie or API token.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UnauthorizedError'

    ValidationErrorResponse:
      description: 'The request body or query string was invalid or contained invalid data.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationError'

    ServerErrorResponse:
      description: An unhandled server error occurred.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServerError'
