services:
  postgres:
    image: postgis/postgis:14-3.4-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=bt_user
      - POSTGRES_PASSWORD=bt_admin1234
    ports:
      - '5432:5432'
    volumes:
      - ./.postgresql/:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U bt_user -d postgres'"]
      interval: 5s
      timeout: 3s
      retries: 3

  core:
    container_name: bottomtime-service
    build:
      context: ./
      dockerfile: Dockerfile.service
    ports:
      - '4800:4800'
    expose:
      - '4800'
    env_file:
      - packages/service/.env
    environment:
      - BT_POSTGRES_URI=postgresql://bt_user:bt_admin1234@postgres:5432/bottomtime_local
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: packages/service/yarn.lock
          target: /app/packages/service/yarn.lock
        - action: sync
          path: packages/service/public/docs/swagger.json
          target: /app/packages/service/public/docs/swagger.json
        - action: rebuild
          path: packages/api/src
          target: /app/packages/api/src
        - action: sync
          path: packages/service/src
          target: /app/packages/service/src

  web:
    container_name: bottomtime-web
    build:
      context: ./
      dockerfile: Dockerfile.web
    ports:
      - '4850:4850'
      - '24678:24678'
    expose:
      - '4850'
      - '24678'
    env_file:
      - packages/web/.env
    environment:
      - BTWEB_API_URL=http://bottomtime-service:4800/
    depends_on:
      core:
        condition: service_started
    develop:
      watch:
        - action: rebuild
          path: packages/web/yarn.lock
          target: /app/packages/web/yarn.lock
        - action: rebuild
          path: packages/api/src
          target: /app/packages/api/src
        - action: sync
          path: packages/web/public
          target: /app/packages/web/public
        - action: sync
          path: packages/web/server
          target: /app/packages/web/server
        - action: sync
          path: packages/web/src
          target: /app/packages/web/src
