services:
  core:
    container_name: bottomtime-core
    build: packages/service/
    ports:
      - '4800:4800'
    expose:
      - '4800'
    env_file:
      - packages/service/.env.defaults
    environment:
      - BT_MONGO_URI=mongodb://mongo:27017/bottomtime
    depends_on:
      - mongo
    networks:
      - backend
      - frontend

  web:
    container_name: bottomtime-web
    build: packages/web/
    ports:
      - '3000:3000'
    expose:
      - '3000'
    env_file:
      - packages/web/.env.defaults
    depends_on:
      - core
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  dbdata:
