FROM node:20

WORKDIR /app

COPY packages/service/* ./packages/service/
COPY packages/api/* ./packages/api/
COPY package.json yarn.lock lerna.json nx.json tsconfig.json ./

RUN yarn install --frozen-lockfile --ignore-scripts --production

ENTRYPOINT ["yarn", "--cwd", "packages/service", "serve"]
