services:
  s3:
    container_name: bottomtime-s3
    image: lphoward/fake-s3
    restart: always
    ports:
      - '4569:4569'
    volumes:
      - ./.s3/:/fakes3_root/

  elasticmq:
    container_name: bottomtime-elasticmq
    build:
      context: ./
      dockerfile: Dockerfile.elasticmq
    ports:
      - '9324:9324'

  postgres:
    container_name: bottomtime-postgres
    image: postgis/postgis:14-3.4-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=bt_user
      - POSTGRES_PASSWORD=bt_admin1234
    ports:
      - '5432:5432'
    volumes:
      - ./.postgresql/:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U bt_user -d postgres'"]
      interval: 5s
      timeout: 3s
      retries: 3

  service:
    container_name: bottomtime-service
    build:
      context: ./
      dockerfile: Dockerfile.service
    ports:
      - '4800:4800'
    expose:
      - '4800'
    env_file:
      - packages/service/.env
    environment:
      - BT_AWS_S3_ENDPOINT=http://s3:4569/
      - BT_AWS_SQS_EMAIL_QUEUE_URL=http://elasticmq:9324/000000000000/emails
      - BT_AWS_SQS_ENDPOINT=http://elasticmq:9324/
      - BT_POSTGRES_URI=postgresql://bt_user:bt_admin1234@postgres:5432/bottomtime_local
    entrypoint: /app/packages/service/bootstrap-docker.sh
    command: []
    working_dir: /app/packages/service
    depends_on:
      s3:
        condition: service_started
      elasticmq:
        condition: service_started
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:4800 || exit 1
      interval: 5s
      retries: 10
      start_period: 15s
      timeout: 5s
    develop:
      watch:
        - action: rebuild
          path: packages/service/yarn.lock
          target: /app/packages/service/yarn.lock
        - action: rebuild
          path: packages/api/src
          target: /app/packages/api/src
        - action: rebuild
          path: packages/common/src
          target: /app/packages/common/src
        - action: sync
          path: packages/service/src
          target: /app/packages/service/src

  web:
    container_name: bottomtime-web
    build:
      context: ./
      dockerfile: Dockerfile.web
    ports:
      - '4850:4850'
      - '24678:24678'
    expose:
      - '4850'
      - '24678'
    env_file:
      - packages/web/.env
    environment:
      - BTWEB_API_URL=http://bottomtime-service:4800/
    depends_on:
      service:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:4850 || exit 1
      interval: 5s
      retries: 10
      start_period: 15s
      timeout: 5s
    develop:
      watch:
        - action: rebuild
          path: packages/web/yarn.lock
          target: /app/packages/web/yarn.lock
        - action: rebuild
          path: packages/api/src
          target: /app/packages/api/src
        - action: sync
          path: packages/web/public
          target: /app/packages/web/public
        - action: sync
          path: packages/web/server
          target: /app/packages/web/server
        - action: sync
          path: packages/web/src
          target: /app/packages/web/src

  docs:
    container_name: bottomtime-docs
    build:
      context: ./
      dockerfile: Dockerfile.docs
    ports:
      - '4890:80'
    expose:
      - '4890'
    environment:
      - BT_AWS_S3_ENDPOINT=http://s3:4569/
      - BT_AWS_SQS_EMAIL_QUEUE_URL=http://elasticmq:9324/000000000000/emails
      - BT_AWS_SQS_ENDPOINT=http://elasticmq:9324/
      - BT_POSTGRES_URI=postgresql://bt_user:bt_admin1234@postgres:5432/bottomtime_local
    develop:
      watch:
        - action: sync+restart
          path: packages/service/public/docs/
          target: /usr/share/nginx/html
