FROM node:20-alpine AS base
RUN corepack enable

FROM base AS build

ENV NPM_CONFIG_CACHE=/tmp/.npm
WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml nx.json lerna.json ./
COPY packages/api/package.json packages/api/tsconfig.json ./packages/api/
COPY packages/common/package.json packages/common/tsconfig.json ./packages/common/
COPY packages/web/package.json packages/web/tsconfig.json packages/web/vite.config.ts packages/web/tailwind.config.js packages/web/postcss.config.js packages/web/index.html packages/web/*.env ./packages/web/

RUN yarn install

COPY packages/api/src/ ./packages/api/src/
COPY packages/common/src/ ./packages/common/src/

COPY packages/web/public/ ./packages/web/public/
COPY packages/web/src/ ./packages/web/src/

RUN yarn build --stream

FROM base AS release
ENV NPM_CONFIG_CACHE=/tmp/.npm

COPY --from=build /app/ /app/
EXPOSE 4850 9231 24678

ENTRYPOINT [ "yarn" ]
CMD [ "dev" ]
