services:
  postgres:
    image: postgis/postgis:14-3.4-alpine
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=bt_user
      - POSTGRES_PASSWORD=bt_admin1234
    ports:
      - '5432:5432'
    networks:
      - backend
    volumes:
      - dbdata:/var/lib/postgresql/data

  core:
    container_name: bottomtime-core
    build:
      context: ./
      dockerfile: Dockerfile.core
    ports:
      - '4800:4800'
    expose:
      - '4800'
    env_file:
      - packages/service/.env
    environment:
      - BT_POSTGRES_URI=postgresql://bt_user:bt_admin1234@postgres:5432/bottomtime_local
    depends_on:
      - postgres
    networks:
      - backend
      - frontend

networks:
  frontend:
  backend:

volumes:
  dbdata:
