org: bottomtime
app: bottomtime
service: bottomtime-service

provider:
  name: aws
  runtime: nodejs20.x
  runtimeManagement: auto
  stage: ${env:NODE_ENV, 'dev'}
  region: ${env:AWS_REGION, 'us-east-1'}
  stackName: ${self:service}-${self:provider.stage}
  stackTags:
    org: ${self:org}
    app: ${self:app}
    service: ${self:service}
  httpApi:
    # id: TODO: Get this from Terraform
    payload: '2.0'
    name: ${self:service}-${self:provider.stage}
    cors: true

plugins:
  - serverless-offline

package:
  individually: true

custom:
  secrets: ${ssm(us-east-1):/aws/reference/secretsmanager/${opt:secrets, 'bt-service-dev'}}

functions:
  main:
    name: ${self:service}-${self:provider.stage}-main
    description: Bottomtime backend service
    handler: dist/sls.handler
    environment:
      BT_AWS_MEDIA_BUCKET: bottomtime-media-${self:provider.stage} # TODO: This should come from Terraform
      BT_BASE_URL: 'http://localhost:8402' # TODO: This should come from Terraform
      BT_LOG_LEVEL: ${env:BT_LOG_LEVEL, 'debug'}
      BT_DISCORD_CLIENT_ID: ${self:custom.secrets.discordClientId}
      BT_DISCORD_CLIENT_SECRET: ${self:custom.secrets.discordClientSecret}
      BT_GITHUB_CLIENT_ID: ${self:custom.secrets.githubClientId}
      BT_GITHUB_CLIENT_SECRET: ${self:custom.secrets.githubClientSecret}
      BT_GOOGLE_CLIENT_ID: ${self:custom.secrets.googleClientId}
      BT_GOOGLE_CLIENT_SECRET: ${self:custom.secrets.googleClientSecret}
      BT_PASSWORD_SALT_ROUNDS: 15
      BT_POSTGRES_REQUIRE_SSL: 'true'
      BT_POSTGRES_URI: ${self:custom.secrets.postgresUri}
      BT_SESSION_COOKIE_DOMAIN: '' # TODO: This should come from Terraform
      BT_SESSION_COOKIE_NAME: ${self:custom.secrets.cookieName}
      BT_SESSION_SECRET: ${self:custom.secrets.sessionSecret}
      BT_SMTP_REPLY_TO: donotreply@bottomti.me
      BT_SMTP_FROM: '"Bottom Time Admin" <admin@bottomti.me>'
      BT_SMTP_HOST: ${self:custom.secrets.smtpHost}
      BT_SMTP_PASSWORD: ${self:custom.secrets.smtpPassword}
      BT_SMTP_USERNAME: ${self:custom.secrets.smtpUsername}
      NODE_ENV: production
    logRetentionInDays: 7
    url:
      cors: true
    package:
      patterns:
        - '!**'
        - dist/**
    events:
      - httpApi:
          method: ANY
          path: '/{proxy+}'
